# Use Amazon Linux 2 from Docker Hub (that our EC2 server currently uses)
image: amazonlinux:2
# Optionally use caching (currently it slows down instead of speeding up, so not using)
#cache:
#  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
#  paths:
#  - workspace/.state/
before_script:
# Install state tool
# We need to use the commands below due to one-line install script having dependencies
  # TODO: use a GitLab environment variable soon rather than hard-coding the URL here.
  - wget https://git.services.nesdis.noaa.gov/ssboxes/science_codes/ncei/cudem/ivert_setup/-/blob/main/ec2/setup.sh
  - chmod +x ./setup.sh
  - ./setup.sh
  # TODO: Add the pytest dependency once we get it set up
  - conda install pylint flake8 --yes
# Download and install the language runtime
#  - state deploy shnewto/learn-python
test:
  script:
# Lint code
    - pylint src
    - flake8 src --statistics --count
# Test code
    # Disable pytest for now until we get it set up.
#    - pytest