[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ivert"
authors = [{name = "Mike MacFerrin", email = "michael.macferrin@colorado.edu"}]
version = "0.1.0"
readme = "README.md"
description = "ICESat-2 Validation of Elevations Reporting Tool (IVERT)"
requires-python = ">=3.9"
keywords = ["icesat2", "elevation", "validation", "ivert"]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha"
]
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "boto3",
    "configparser"
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/", "src/utils/"]

[tool.hatch.build.targets.sdist]
include = [
    "src/",
    "src/utils/",
    "config/*.ini",
    "config/*.sql",
    "LICENSE",
    "data/empty_tile.tif"
]

[project.entry-points."ivert"]
ivert = "ivert_client:ivert_client_cli"

[project.scripts]
ivert = "ivert_client:ivert_client_cli"
#s3 = "srcs3:s3_cli"

#[project.entry-points."s3"]
#s3 = "srcs3:s3_cli"