[DEFAULT]
# In the code from configparser.Config(), paths will be automatically detected by looking for a folder delimeter
# ("/" on linux/cygwin, "\" on Windows). If the paths are absolute (starting with the root drive), they will be
# assigned as absolute paths. To avoid the conversion to absolute paths, wrap the string in quotes (" ") and it'll
# just be read as-is.

# The base directory of this project. All relative directory paths are relative to the location of THIS FILE.
# The utils.configfile utility will turn this into an absolute path upon reading it.
# An exception is if the variable name begins with "s3_". In that case it's an S3 bucket path and will not be
# converted to an absolute path.

# This value is harded-coded, not editable in user settings.
project_base_directory = ../

# The version will be dynamically filled in from the VERSION file at runtime. Do not change here.
# This value is harded-coded, not editable in user settings.
ivert_version = None

# ICESat-2 ATL points are given in 'seconds since the atlas_spd_epoch', which is Jan 1, 2018 00:00:00 Zulu time.
# In Python, convert this to a datetime.
# This value is harded-coded, not editable in user settings.
atlas_sdp_epoch = 2018-01-01T00:00:00Z

# All the following values are defaults only, and can be reset using the "ivert setup" command.

dem_default_ndv = NaN

nsidc_atl_version = "007"

user_data_directory = ~/.ivert
user_configfile = %(user_data_directory)s/user_config.ini

# Where to store icesat2, OpenStreetMap, and other data needed when building the database and/or processing granules.
cache_directory = %(user_data_directory)s/cache

icesat2_granules_directory = %(user_data_directory)s/icesat2/granules
# By default, raw icesat2 granule downloads go in the same place as the cache directory for other data. It can be
# separated here if you want.
icesat2_download_directory = %(cache_directory)s
icesat2_granules_gpkg = %(user_data_directory)s/icesat2/icesat2_granules_database.gpkg
icesat2_granules_blosc = %(user_data_directory)s/icesat2/icesat2_granules_database.blosc
# The CSV file to use to keep track of previous icesat2 requests.
icesat2_requests_csv = %(user_data_directory)s/icesat2/requests.csv
# The last date (YYYYMMDD) for which ATL24 bathymetry classifications are available.
# ATL24 data is only reprocessed periodically. Update this via "ivert setup atl24_date_cutoff=YYYYMMDD"
# when a new version of ATL24 data becomes available.
atl24_date_cutoff = 20241107
# IVERT vertical datum. Save the photons in the database in EGM2008 geoid, or WGS84 ellipsoid heights.
# The two choices for this variable are "geoid" or "ellipsoid".
# All photons will be converted into the DEM's vertical datum upon validation.
# "ellipsoid" : WGS84 Ellipsoid heights (EPSG: 4979)
# "geoid"     : EGM 2008 Geoid heights (EPSG: 3855)
icesat2_vertical_datum="ellipsoid"

# ivert_results_subdir is a relative directory, where (by default) ivert results are written when dems are validated.
# This is a directory relative to the path of the DEMs being validated, not the current working directory of the process.
ivert_results_subdir = ivert_results/

# verbosity level. Sets "logging.info" to the following levels of verbosity.
# Choices are:
# "debug": See detailed output from all code and libraries. Extremely verbose, probably annoying for general execution
#             but good for debugging.
# "info": See steps happening as they occur in the code.
# "warning": Omit info statements, but print warning statements to the screen (to stderr). This is "quiet" mode.
# "error": Only print breaking errors to stderr. This is "very-quiet" mode.
verbosity = info

# The ivert github repository, and the git/pip commands to install or upgrade it.
# TODO: Change this when we port over to the continuous-dems community
ivert_github_repo = https://github.com/ciresdem/IVERT.git
ivert_pip_install_command = "pip install --user git+%(ivert_github_repo)s"
ivert_pip_upgrade_command = "pip install --upgrade --user git+%(ivert_github_repo)s"

