[DEFAULT]
# In the code from configparser.Config(), paths will be automatically detected by looking for a folder delimeter
# ("/" on linux/cygwin, "\" on Windows). If the paths are absolute (starting with the root drive), they will be
# assigned as absolute paths. To avoid the conversion to absolute paths, wrap the string in quotes (" ") and it'll
# just be read as-is.

# The base directory of this project. All relative directory paths are relative to the location of THIS FILE.
# The utils.configfile utility will turn this into an absolute path upon reading it.
# An exception is if the variable name begins with "s3_". In that case it's an S3 bucket path and will not be
# converted to an absolute path.

# This value is harded-coded, not editable in user settings.
project_base_directory = ../

# The version will be dynamically filled in from the VERSION file at runtime. Do not change here.
# This value is harded-coded, not editable in user settings.
ivert_version = None

# ICESat-2 ATL points are given in 'seconds since the atlas_spd_epoch', which is Jan 1, 2018 00:00:00 Zulu time.
# In Python, convert this to a datetime.
# This value is harded-coded, not editable in user settings.
atlas_sdp_epoch = 2018-01-01T00:00:00Z

# All the following values are defaults only, and can be reset using the "ivert setup" command.

dem_default_ndv = -99999.0

nsidc_atl_version = "007"

user_data_directory = ~/.ivert
user_configfile = %(user_data_directory)s/user_config.ini

# Where to store icesat2, OpenStreetMap, and other data needed when building the database and/or processing granules.
cache_directory = %(user_data_directory)s/cache

icesat2_granules_directory = %(user_data_directory)s/icesat2/granules
# By default, raw icesat2 granule downloads go in the same place as the cache directory for other data. It can be
# separated here if you want.
icesat2_download_directory = %(cache_directory)s
icesat2_granules_gpkg = %(user_data_directory)s/icesat2/icesat2_granules_database.gpkg
icesat2_granules_blosc = %(user_data_directory)s/icesat2/icesat2_granules_database.blosc
# The CSV file to use to keep track of previous icesat2 requests.
icesat2_requests_csv = %(user_data_directory)s/icesat2/requests.csv


# The ivert github repository, and the git/pip commands to install or upgrade it.
# TODO: Change this when we port over to the continuous-dems community
ivert_github_repo = https://github.com/ciresdem/IVERT.git
ivert_pip_install_command = "pip install --user git+%(ivert_github_repo)s"
ivert_pip_upgrade_command = "pip install --upgrade --user git+%(ivert_github_repo)s"

